algoritmo "Grade 3 Aula 2 multiplicador"
// Função :  Enquanto faca
// Autor :
// Data : 19/03/2022
// Seção de Declarações 
var
    numero,multiplicador: inteiro
inicio
      escreval("Informe um número")
          leia(numero)
             multiplicador <- 1
          enquanto (multiplicador<=100) faca
             escreval(numero," x ",multiplicador," = ", numero*multiplicador)
                    multiplicador <- multiplicador+1

             fimenquanto





fimalgoritmo
